kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "coralogix-fluentd.name" . }}-configs
  namespace: kube-system
  labels:
    k8s-app: {{ template "coralogix-fluentd.fullname" . }}
    k8s-app-version: {{ .Chart.AppVersion }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  fluent.conf: |
    @include conf/*.conf
  kubernetes.conf: |
    <source>
      @type tail
      @label @kubernetes_containers_logs
      path /var/log/containers/*.log
      pos_file /var/log/containers.log.pos
      time_format %Y-%m-%dT%H:%M:%S.%NZ
      tag containers.*
      read_from_head true
      format json
      time_format %Y-%m-%dT%H:%M:%S.%NZ
    </source>
    <source>
      @type tail
      @label @kubernetes_internal_logs
      format none
      path /var/log/etcd.log
      pos_file /var/log/etcd.log.pos
      tag kubernetes.etcd
    </source>
    <source>
      @type tail
      @label @kubernetes_internal_logs
      format kubernetes
      multiline_flush_interval 5s
      path /var/log/kubelet.log
      pos_file /var/log/kubelet.log.pos
      tag kubernetes.kubelet
    </source>
    <source>
      @type tail
      @label @kubernetes_internal_logs
      format kubernetes
      multiline_flush_interval 5s
      path /var/log/kube-proxy.log
      pos_file /var/log/kube-proxy.log.pos
      tag kubernetes.kube-proxy
    </source>
    <source>
      @type tail
      @label @kubernetes_internal_logs
      format kubernetes
      multiline_flush_interval 5s
      path /var/log/kube-apiserver.log
      pos_file /var/log/kube-apiserver.log.pos
      tag kubernetes.kube-apiserver
    </source>
    <source>
      @type tail
      @label @kubernetes_internal_logs
      format kubernetes
      multiline_flush_interval 5s
      path /var/log/kube-controller-manager.log
      pos_file /var/log/kube-controller-manager.log.pos
      tag kubernetes.kube-controller-manager
    </source>
    <source>
      @type tail
      @label @kubernetes_internal_logs
      format kubernetes
      multiline_flush_interval 5s
      path /var/log/kube-scheduler.log
      pos_file /var/log/kube-scheduler.log.pos
      tag kubernetes.kube-scheduler
    </source>
    <source>
      @type tail
      @label @kubernetes_internal_logs
      format kubernetes
      multiline_flush_interval 5s
      path /var/log/rescheduler.log
      pos_file /var/log/rescheduler.log.pos
      tag kubernetes.rescheduler
    </source>
    <source>
      @type tail
      @label @kubernetes_internal_logs
      format kubernetes
      multiline_flush_interval 5s
      path /var/log/glbc.log
      pos_file /var/log/glbc.log.pos
      tag kubernetes.glbc
    </source>
    <source>
      @type tail
      @label @kubernetes_internal_logs
      format kubernetes
      multiline_flush_interval 5s
      path /var/log/cluster-autoscaler.log
      pos_file /var/log/cluster-autoscaler.log.pos
      tag kubernetes.cluster-autoscaler
    </source>
    <label @kubernetes_internal_logs>
      <filter kubernetes.**>
        @type kubernetes_metadata
      </filter>
      <match kubernetes.**>
        @type coralogix
        privatekey "#{ENV['PRIVATE_KEY']}"
        appname "#{ENV['APP_NAME']}"
        subsystemname "Kubernetes"
        is_json true
      </match>
    </label>
    <label @kubernetes_containers_logs>
      <filter containers.**>
        @type kubernetes_metadata
      </filter>
      <match containers.**>
         @type rewrite_tag_filter
         <rule>
           key $.kubernetes.container_name
           pattern ^(.+)$
           tag $1.${tag}
         </rule>
      </match>
      <match {heapster,influxdb,grafana,fluentd}.containers.**>
        @type null
      </match>
      <match *.containers.**>
        @type coralogix
        privatekey "#{ENV['PRIVATE_KEY']}"
        appname "$kubernetes.namespace_name"
        subsystemname "$kubernetes.container_name"
        log_key_name {{ .Values.coralogix.log_key_name }}
        is_json {{ .Values.coralogix.is_json }}
      </match>
    </label>