kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "coralogix-fluentd.name" . }}-configs
  namespace: {{ .Values.namespace }}
  labels:
    k8s-app: {{ template "coralogix-fluentd.fullname" . }}
    k8s-app-version: {{ .Chart.AppVersion }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  fluent.conf: |
    #@include conf/kubernetes.conf
    #@include conf/graylog.conf
    @include conf/syslog.conf
    @include conf/http.conf
    @include /conf/*.conf
  kubernetes.conf: |
    <system>
      log_level {{ if .Values.coralogix.debug }}debug{{ else }}warn{{ end }}
    </system>
