{{- if not .Values.daemonset }}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "coralogix-fluentd.name" . }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    k8s-app: {{ template "coralogix-fluentd.fullname" . }}
    k8s-app-version: {{ .Chart.AppVersion }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    kubernetes.io/cluster-service: "true"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      k8s-app: {{ template "coralogix-fluentd.fullname" . }}
  template:
    metadata:
      labels:
        k8s-app: {{ template "coralogix-fluentd.fullname" . }}
        k8s-app-version: {{ .Chart.AppVersion }}
        kubernetes.io/cluster-service: "true"
      annotations:
{{ toYaml .Values.annotations | indent 8 }}
    spec:
      containers:
      - name: fluentd-coralogix
        image: {{ .Values.container.image.repository }}:{{ .Values.container.image.tag }}
        imagePullPolicy: {{ .Values.container.image.pullPolicy }}
        envFrom:
        - secretRef:
           name: {{ template "coralogix-fluentd.name" . }}-account-secrets
        env:
          {{- range $key, $value := .Values.env }}
          - name: {{ $key | quote }}
            value: {{ $value | quote }}
          {{- end }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
        ports:
          {{- if .Values.service.fluentd.enabled }}
        - containerPort: 24224
          protocol: TCP
          name: fluentd
          {{- end }}
          {{- if .Values.service.http.enabled }}
        - containerPort: 9880
          protocol: TCP
          name: http
          {{- end }}
          {{- if .Values.service.syslog.enabled }}
        - containerPort: 5140
          protocol: UDP
          name: syslog
          {{- end }}
          {{- if .Values.service.graylog.enabled }}
        - containerPort: 12201
          protocol: UDP
          name: graylog
         {{- end }}
        livenessProbe:
          httpGet:
            # Use percent encoding for query param.
            # The value is {"log": "health check"}.
            # the endpoint itself results in a new fluentd
            # tag 'fluentd.pod-healthcheck'
            path: /fluentd.pod.healthcheck?json=%7B%22log%22%3A+%22health+check%22%7D
            port: 9880
          initialDelaySeconds: 5
          timeoutSeconds: 1
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluentd-config
          mountPath: /fluentd/etc/fluent.conf
          subPath: fluent.conf
        - name: fluentd-config
          mountPath: /fluentd/etc/conf/kubernetes.conf
          subPath: kubernetes.conf
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: fluentd-config
        configMap:
          name: {{ template "coralogix-fluentd.name" . }}-configs
      {{- if .Values.rbac.create }}
      serviceAccount: {{ template "coralogix-fluentd.name" . }}-service-account
      serviceAccountName: {{ template "coralogix-fluentd.name" . }}-service-account
      {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- end }}
