##  Coralogix Account secrets
PRIVATE_KEY:
APP_NAME: $namespace_name
SUB_SYSTEM: $container_name

## Namespace to install at
namespace: default

## Coralogix output settings
coralogix:
  # log_key_name: "parsed"
  # timestamp_key_name: ""
  is_json: true
  force_compression: false
  debug: false

## Pod settings
container:
  image:
    repository: docker.io/coralogixrepo/fluentd-coralogix-image
    tag: 1.1.4
    pullPolicy: Always
  resources:
    requests:
      cpu: 100m
      memory: 400Mi

## Environment variables
env:
  CORALOGIX_LOG_URL: "https://test.coralogix.com/api/v1/logs"

## Security settings
rbac:
  create: true

## FluentD service settings
service:
  fluentd:
    enabled: true
    port: 24224
  http:
    enabled: false
    port: 9880
  syslog:
    enabled: false
    port: 5140
  graylog:
    enabled: false
    port: 12201
  clusterIP: None

# Kind Daemonset or Deployment
kind: Deployment
replicaCount: 1


annotations:
  fluentbit.io/exclude: "true"

tolerations:
- key: "role"
  operator: "Equal"
  value: "fluentd"
  effect: "NoSchedule"

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: role
          operator: In
          values:
          - fluentd
