{
 "title": "Fluent logs",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Environment", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(kube_pod_info{namespace=~\"$namespace\"}, pod)"
   },
   {
    "name": "fluentd",
    "label": "FluentD",
    "query": "label_values(kube_pod_info{namespace=~\"$namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "FluentD",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(pod_name) (container_memory_usage_bytes{pod_name=~\"$fluentd\", container_name!=\"POD\"})",
       "legendFormat": "{{pod_name}} - Current"
      },
      {
       "expr": "sum by (pod_name) (kube_pod_container_resource_requests_memory_bytes{pod=~\"$fluentd\"})",
       "legendFormat": "{{pod_name}} - Requested"
      },
      {
       "expr": "sum by (pod_name) (kube_pod_container_resource_limits_memory_bytes{pod=~\"$fluentd\"})",
       "legendFormat": "{{pod_name}} - Limit"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (pod_name)(rate(container_cpu_usage_seconds_total{image!=\"\",container_name!=\"POD\",pod_name=~\"$fluentd\"}[5m]))",
       "legendFormat": "{{ pod_name }}"
      }
     ]
    },
    {
     "title": "Network I/O",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum by (pod_name) (rate(container_network_receive_bytes_total{pod_name=~\"$fluentd\"}[1m])))",
       "legendFormat": "{{ pod_name }}"
      }
     ]
    },
    {
     "title": "Memory Usage Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(pod_name) (rate(container_memory_usage_bytes{pod_name=~\"$fluentd\", container_name!=\"POD\"}[1m]))",
       "legendFormat": "{{pod_name}} - {{container_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "fluent-bit",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(pod_name) (container_memory_usage_bytes{pod_name=~\"$pod\", container_name!=\"POD\"})",
       "legendFormat": "{{pod_name}} - Current"
      },
      {
       "expr": "sum by (pod_name) (kube_pod_container_resource_requests_memory_bytes{pod=~\"$pod\"})",
       "legendFormat": "{{pod_name}} - Requested"
      },
      {
       "expr": "sum by (pod_name) (kube_pod_container_resource_limits_memory_bytes{pod=~\"$pod\"})",
       "legendFormat": "{{pod_name}} - Limit"
      }
     ]
    },
    {
     "title": "Memory Usage Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(pod_name) (rate(container_memory_usage_bytes{pod_name=~\"$pod\", container_name!=\"POD\"}[1m]))",
       "legendFormat": "{{pod_name}} - {{container_name}}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (pod_name)(rate(container_cpu_usage_seconds_total{image!=\"\",container_name!=\"POD\",pod_name=~\"$pod\"}[5m]))",
       "legendFormat": "{{ pod_name }}"
      }
     ]
    },
    {
     "title": "Network I/O",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum by (pod_name) (rate(container_network_receive_bytes_total{pod_name=~\"$pod\"}[1m])))",
       "legendFormat": "{{ pod_name }}"
      }
     ]
    }
   ]
  }
 ]
}