##  Coralogix Account secrets
PRIVATE_KEY: 6411e033-3439-d71c-542b-0d45419d6b30
APP_NAME: shauli-test
SUB_SYSTEM: fluent-bit-test

## Namespace to install at
namespace: default

## Namespace to install at
namespace: default

## Coralogix output settings
coralogix:
  # log_key_name: ""
  # timestamp_key_name: ""
  is_json: true
  force_compression: false
  debug: false

## Pod settings
container:
  image:
    repository: docker.io/coralogixrepo/fluentd-coralogix-image
    tag: latest
    pullPolicy: Always
  resources:
    limits:
      cpu: 100m
      memory: 400Mi
    requests:
      cpu: 100m
      memory: 400Mi

## Environment variables
env:

## Security settings
rbac:
  create: true

## Node settings
tolerations:
  - key: node-role.kubernetes.io/master
    effect: NoSchedule

## FluentD service settings
service:
  fluentd:
    enabled: true
    port: 24224
  http:
    enabled: false
    port: 9880
  syslog:
    enabled: false
    port: 5140
  graylog:
    enabled: false
    port: 12201
  clusterIP: None

# Kind Daemonset or Deployment
kind: Deployment 
replicaCount: 1
