##  Coralogix Account secrets
PRIVATE_KEY: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
APP_NAME: $kubernetes.namespace_name
SUB_SYSTEM: $kubernetes.container_name

## Coralogix output settings
coralogix:
  # log_key_name: ""
  # timestamp_key_name: ""
  is_json: true
  force_compression: false
  debug: false
  proxy: {}
  #  host: localhost
  #  port: 3128
  #  user: root
  #  password: strong_pass

## Pod settings
container:
  image:
    repository: docker.io/coralogixrepo/fluentd-coralogix-image
    tag: 1.1.6
    pullPolicy: Always
  resources:
    limits:
      cpu: 100m
      memory: 400Mi
    requests:
      cpu: 100m
      memory: 400Mi
  private_registry: false
  pull_secrets: []

## Security settings
rbac:
  create: false

## Node settings
tolerations:
  - key: node-role.kubernetes.io/master
    effect: NoSchedule

## FluentD service settings
service:
  fluentd:
    enabled: true
    port: 24224
  http:
    enabled: true
    port: 9880
  syslog:
    enabled: true
    port: 5140
  graylog:
    enabled: true
    port: 12201
  clusterIP: None

## Plugins settings
plugins:
  sampling:
    enabled: false
    interval: 10
