apiVersion: v1
kind: Secret
metadata:
  name: {{ template "coralogix-fluentd.name" . }}-account-secrets
  namespace: kube-system
  labels:
    k8s-app: {{ template "coralogix-fluentd.fullname" . }}
    k8s-app-version: {{ .Chart.AppVersion }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  PRIVATE_KEY: {{ .Values.PRIVATE_KEY | b64enc | quote }}
  APP_NAME: {{ .Values.APP_NAME | b64enc | quote }}
  SUB_SYSTEM: {{ .Values.SUB_SYSTEM | b64enc | quote }}