apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd-coralogix-service-account
  namespace: apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-coralogix-daemonset
  namespace: coralogix-fluentd
  labels:
    k8s-app: fluentd-coralogix-logger
spec:
  selector:
    matchLabels:
      k8s-app: fluentd-coralogix-logger
  template:
    metadata:
      labels:
        k8s-app: fluentd-coralogix-logger
    spec:
      containers:
      - name: fluentd-coralogix
        image: coralogixrepo/coralogix-fluentd-multiarch:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 24224
          protocol: TCP
          name: fluentd
        - containerPort: 9880
          protocol: TCP
          name: http
        - containerPort: 5140
          protocol: UDP
          name: syslog
        - containerPort: 12201
          protocol: UDP
          name: graylog
        envFrom:
        - secretRef:
           name: fluentd-coralogix-account-secrets
        resources:
          limits:
            cpu: 800m
            memory: 900Mi
          requests:
            cpu: 800m
            memory: 900Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluentd-config
          mountPath: /fluentd/etc/fluent.conf
          subPath: fluent.conf
        - name: fluentd-config
          mountPath: /fluentd/etc/conf/kubernetes.conf
          subPath: kubernetes.conf
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: fluentd-config
        configMap:
          name: fluentd-coralogix-configs
      serviceAccount: fluentd-coralogix-service-account
      serviceAccountName: fluentd-coralogix-service-account
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule

  labels:
    k8s-app: fluentd-coralogix-logger
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluentd-coralogix-service-account-role
  namespace: fluentd-coralogix
  labels:
    k8s-app: fluentd-coralogix-logger
rules:
  # Allow FluentD-Coralogix-Logger to get 'fluentd-coralogix-account-secrets' secret.
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["fluentd-coralogix-account-secrets"]
  verbs: ["get"]
  # Allow FluentD-Coralogix-Logger to get 'fluentd-coralogix-configs' config map.
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["fluentd-coralogix-configs"]
  verbs: ["get"]
  # Allow FluentD-Coralogix-Logger to get cluster info.
- apiGroups: [""]
  resources: ["namespaces", "pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluentd-coralogix-service-account
  namespace: fluentd-coralogix
  labels:
    k8s-app: fluentd-coralogix-logger
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluentd-coralogix-service-account-role
subjects:
- kind: ServiceAccount
  name: fluentd-coralogix-service-account
  namespace: fluentd-coralogix
