kind: Service
apiVersion: v1
metadata:
  name: fluentd-coralogix-service
  namespace: fluentd-coralogix
  labels:
    k8s-app: fluentd-coralogix-logger
spec:
  selector:
    k8s-app: fluentd-coralogix-logger
  ports:
    - port: 24224
      targetPort: 24224
      protocol: TCP
      name: fluentd
    - port: 9880
      targetPort: 9880
      protocol: TCP
      name: http
    - port: 5140
      targetPort: 5140
      protocol: UDP
      name: syslog
    - port: 12201
      targetPort: 12201
      protocol: UDP
      name: graylog
  clusterIP: None