apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd-coralogix-service-account
  namespace: kube-system
  labels:
    k8s-app: fluentd-coralogix-logger
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluentd-coralogix-service-account-role
  namespace: kube-system
  labels:
    k8s-app: fluentd-coralogix-logger
rules:
  # Allow FluentD-Coralogix-Logger to get 'fluentd-coralogix-account-secrets' secret.
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["fluentd-coralogix-account-secrets"]
  verbs: ["get"]
  # Allow FluentD-Coralogix-Logger to get 'fluentd-coralogix-configs' config map.
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["fluentd-coralogix-configs"]
  verbs: ["get"]
  # Allow FluentD-Coralogix-Logger to get cluster info.
- apiGroups: [""]
  resources: ["namespaces", "pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluentd-coralogix-service-account
  namespace: kube-system
  labels:
    k8s-app: fluentd-coralogix-logger
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluentd-coralogix-service-account-role
subjects:
- kind: ServiceAccount
  name: fluentd-coralogix-service-account
  namespace: kube-system
